pipeline:
    environment:
        RELEASE_TRAIN: 1    
    artifacts: 
      github:
          condition:
            branch_name: ^v[0-9.\-]+$
          assets:
            - name: cci-ont-releasetrain-api.zip
              path: ./releasetrain-api/
              label: 'Versão completa buildada da API'
            - name: cas.war
              path: legradle/build/libs/
      jenkins:
          assets:         
          - name: cas.war
            path: legradle/build/libs/
          - name: sso.jar
            path: springboot/target/
    projects:      
      - name: ss0
        folder: ./springboot
        template: 
          - maven
          - docker
        docker:
          - condition: 
              branch_name: ^teste2$
            repository: projects
            imageName: sso-test
            projectVersionAsTag: true
            tags:
              - sso-teste
              - latest