project:
    name: ss0
    type: maven

tests:
    - test1:
        actions: test

docker:
    alwaysLatest: true
    dockerfile: Dockerfile
    tags:
        - xablau
        - xablau2

artifacts: 
    jenkins:
        - name: sso.jar
          path: target/
    repository_management:
        - name: sso.jar
          path: target/
          type: java    