- folder: springboot
  configuration:    
    project:
        name: ss0
        type: maven
    docker:
        alwaysLatest: true
        dockerfile: Dockerfile 
        tags:
            - xablau
            - xablau2
    artifacts: 
        jenkins:
            - name: version.txt
              path: ./
        github:
            - name: version.txt
              path: ./
              label: 'Minha versão'
