- folder: legradle
  configuration:
    project:
        name: caszinho
        type: gradle    
    container:
      image: gradle:jdk11
    docker: 
        alwaysLatest: true
        dockerfile: Dockerfile
        tags:
            - casGradle1
    artifacts: 
        jenkins:  
            - name: cas.war
              path: build/libs/
            - name: version.txt
              path: ./
        github:
            - name: cas*.war
              path: build/libs/
