pipeline:
    environment:
        RELEASE_TRAIN: 1    
    artifacts: 
      github:
          assets:
            - name: cci-ont-releasetrain-api.zip
              path: ./releasetrain-api/
              label: 'Versão completa buildada da API'
            - name: cas.war
              path: legradle/build/libs/
      jenkins:  
          - name: cas.war
            path: legradle/build/libs/
          - name: sso.jar
            path: springboot/target/
    projects:
      - name: caszinho
        folder: ./legradle
        template: gradle
        definition:
           environment:
              GRADLE_BIN: ./gradlew
           container:
              image: gradle:jdk11
           
      - name: cci-ont-releasetrain-api
        folder: releasetrain-api
        template: node
      - name: ss0
        folder: ./springboot
        template: maven