debug: true
server:
  port: 8899
  servlet:
    context-path: /mvchat 

logging:
  level:
    org.springframework: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: INFO

#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          mvcap:
#            client-id: mvchat
#            client-secret: pdRrxjfgraja
#            authorization-grant-type: authorization_code
#        provider:
#          mvcap:            
#            authorization-uri: https://extras.consulfarmasaude.com.br/mvcap/oauth2.0/authorize
#            token-uri: https://extras.consulfarmasaude.com.br/mvcap/oauth2.0/accessToken
#            user-info-uri: https://extras.consulfarmasaude.com.br/mvcap/oauth2.0/profile            
#            user-info-authentication-method: header
#            user-name-attribute: id
            
security:
  oauth2:
    client:
      clientId: mvchat
    resource:
      user-info-uri: https://extras.consulfarmasaude.com.br/mvcap/oauth2.0/profile
      
    
      
