debug: true
server:
  port: 8899
  servlet:
    context-path: /mvchat 

logging:
  level:
    org.springframework: INFO
    org.springframework.security: DEBUG

spring:
  security:
    oauth2:
      client:
        registration:
          mvcap:
            client-id: mvchat
            client-secret: pdRrxjfgraja
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          mvcap:
            authorization-uri: https://extras.consulfarmasaude.com.br/mvcap/oauth2.0/authorize
            token-uri: https://extras.consulfarmasaude.com.br/mvcap/oauth2.0/accessToken
            user-info-uri: https://extras.consulfarmasaude.com.br/mvcap/oauth2.0/profile            
            user-info-authentication-method: header
            user-name-attribute: login
            
        