name: CI
on: [push]
jobs:
  buildspring:
    container:
        image: openjdk:11
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Build with Gradle
        run: cd springboot/ && mvn build
  buildnode:
    container:
          image: node:12
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Build 
        run: cd nodezao/ && npm ci && npm run build
